<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ocl" nsURI="http://www.eclipse.org/fennec/m2x/ocl/1.0" nsPrefix="ocl">
  <eAnnotations source="Version">
    <details key="value" value="1.0"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="complianceLevel" value="21.0"/>
    <details key="oSGiCompatible" value="true"/>
    <details key="basePackage" value="org.eclipse.fennec.m2x.model"/>
    <details key="resource" value="XMI"/>
    <details key="copyrightText" value="******************************************************************&#xA;Copyright (c) 2026 Contributors to the Eclipse Foundation.&#xA;&#xA;This program and the accompanying materials are made&#xA;available under the terms of the Eclipse Public License 2.0&#xA;which is available at https://www.eclipse.org/legal/epl-2.0/&#xA;&#xA;SPDX-License-Identifier: EPL-2.0&#xA;&#xA;Contributors:&#xA;  Data In Motion Consulting - initial implementation&#xA;******************************************************************"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EEnum" name="CollectionKind">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The kind of a collection type or collection literal (OCL v2.4 Section 8.2)."/>
    </eAnnotations>
    <eLiterals name="Collection"/>
    <eLiterals name="Set" value="1"/>
    <eLiterals name="OrderedSet" value="2"/>
    <eLiterals name="Bag" value="3"/>
    <eLiterals name="Sequence" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ConstraintKind">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The kind of an OCL constraint: invariant, pre/postcondition, body, initial/derived value, or definition."/>
    </eAnnotations>
    <eLiterals name="inv"/>
    <eLiterals name="pre" value="1"/>
    <eLiterals name="post" value="2"/>
    <eLiterals name="body" value="3"/>
    <eLiterals name="init" value="4"/>
    <eLiterals name="derive" value="5"/>
    <eLiterals name="def" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OclType" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Abstract base class for all OCL types. Each type carries a name used in diagnostics and pretty-printing."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrimitiveType" eSuperTypes="#//OclType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An OCL primitive type: Boolean, Integer, Real, String, or UnlimitedNatural (OCL v2.4 Section 8.2.1)."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnyType" eSuperTypes="#//OclType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The OclAny type, supertype of all other types except OclVoid and OclInvalid (OCL v2.4 Section 8.2.2)."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VoidType" eSuperTypes="#//OclType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The OclVoid type, which has a single instance 'null'. Conforms to all other types (OCL v2.4 Section 8.2.3)."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InvalidType" eSuperTypes="#//OclType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The OclInvalid type, which has a single instance 'invalid'. Represents evaluation errors (OCL v2.4 Section 8.2.4)."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CollectionType" eSuperTypes="#//OclType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Base class for OCL collection types. Carries the element type and collection kind (OCL v2.4 Section 8.2.5)."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elementType" eType="#//OclType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//CollectionKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SetType" eSuperTypes="#//CollectionType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The Set(T) collection type: unordered, no duplicates."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OrderedSetType" eSuperTypes="#//CollectionType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The OrderedSet(T) collection type: ordered, no duplicates."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BagType" eSuperTypes="#//CollectionType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The Bag(T) collection type: unordered, allows duplicates."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SequenceType" eSuperTypes="#//CollectionType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The Sequence(T) collection type: ordered, allows duplicates."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MapType" eSuperTypes="#//OclType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The Map(K, V) type. OCL v2.5 extension for key-value mappings."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="keyType" eType="#//OclType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valueType" eType="#//OclType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TupleType" eSuperTypes="#//OclType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An OCL tuple type defined by a set of named, typed parts. E.g. Tuple(name: String, age: Integer) (OCL v2.4 Section 8.2.6)."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedParts" upperBound="-1"
        eType="#//TuplePart" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MessageType" eSuperTypes="#//OclType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The type of an OclMessage, parameterized by the operation or signal that was sent (OCL v2.4 Section 8.2.7)."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referredOperation" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EOperation">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The operation that this message type refers to, or null if it refers to a signal."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referredSignal" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClassifier">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The signal that this message type refers to, or null if it refers to an operation. Typed as EClassifier since Ecore has no signal concept."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassifierType" eSuperTypes="#//OclType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Wraps an Ecore EClassifier as an OCL type, used when the OCL type system refers to a user-model classifier."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referredClassifier" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClassifier">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The Ecore classifier (EClass, EDataType, EEnum) that this OCL type wraps."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OclExpression" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Abstract base class for all OCL expression AST nodes. Every expression has a resolved type (OCL v2.4 Section 8.3)."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//OclType">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The resolved type of this expression, assigned during type checking."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CallExp" abstract="true" eSuperTypes="#//OclExpression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Abstract base for all call expressions. A call has a source expression, and may be implicit or use safe navigation (OCL v2.4 Section 8.3.1)."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedSource" eType="#//OclExpression"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The source expression on which this call is evaluated. E.g. in 'self.name', 'self' is the source."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isImplicit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="True if the source was not explicitly written in the OCL text but inserted by the compiler (e.g. implicit 'self')."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isSafe" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="OCL v2.5: true for safe navigation operators (?. and ?->) which return null instead of OclInvalid when the source is null."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureCallExp" abstract="true" eSuperTypes="#//CallExp">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Abstract base for property and operation calls on a model element (OCL v2.4 Section 8.3.2)."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isPre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="True if the @pre suffix is used, referring to the pre-state value in a postcondition context."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyCallExp" eSuperTypes="#//FeatureCallExp">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Access to a structural feature (attribute or reference) of the source object. E.g. 'self.name' (OCL v2.4 Section 8.3.3)."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referredProperty" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStructuralFeature">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The Ecore structural feature (EAttribute or EReference) being accessed."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NavigationCallExp" abstract="true" eSuperTypes="#//FeatureCallExp">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Abstract base for navigation expressions with optional qualifiers. Serves as supertype for AssociationClassCallExp (OCL v2.4 Section 8.3)."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="qualifiers" upperBound="-1"
        eType="#//OclExpression" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Optional qualifier expressions for disambiguating navigation along qualified associations."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AssociationClassCallExp" eSuperTypes="#//NavigationCallExp">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Navigation to an association class instance. The referredAssociationClass identifies the target association class (OCL v2.4 Section 8.3.5)."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referredAssociationClass" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClassifier">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The association class being navigated to. Typed as EClassifier (UML-independent); the ocl.uml bundle casts at runtime."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperationCallExp" eSuperTypes="#//FeatureCallExp">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Invocation of an operation, including infix operators (+, =, etc.) and built-in OCL operations (OCL v2.4 Section 8.3.4)."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The name of the called operation (e.g. 'size', '+', 'oclIsKindOf'). Always set by the parser, regardless of whether referredOperation is null. Used for stdlib dispatch in the evaluator."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedArguments" upperBound="-1"
        eType="#//OclExpression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referredOperation" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EOperation">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The Ecore operation being called. May be null for built-in OCL operations that have no EOperation counterpart."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LoopExp" abstract="true" eSuperTypes="#//CallExp">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Abstract base for iterator and iterate expressions that loop over a collection source (OCL v2.4 Section 8.3.5)."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedBody" eType="#//OclExpression"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The body expression evaluated for each element of the source collection."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedIterators" upperBound="-1"
        eType="#//Variable" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The iterator variable(s) bound to successive elements of the source collection."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IteratorExp" eSuperTypes="#//LoopExp">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A named iterator expression such as select, reject, collect, forAll, exists, any, one, isUnique, sortedBy, closure (OCL v2.4 Section 8.3.6)."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The iterator name, e.g. 'select', 'collect', 'forAll', 'exists'."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IterateExp" eSuperTypes="#//LoopExp">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The iterate expression: the most general collection loop with an explicit accumulator variable (OCL v2.4 Section 8.3.7)."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedResult" eType="#//Variable"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The accumulator variable that holds the intermediate and final result of the iteration."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralExp" abstract="true" eSuperTypes="#//OclExpression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Abstract base for all literal (constant value) expressions (OCL v2.4 Section 8.3.8)."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrimitiveLiteralExp" abstract="true"
      eSuperTypes="#//LiteralExp">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Abstract base for literals of primitive types: Integer, Real, Boolean, String, UnlimitedNatural, and null."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerLiteralExp" eSuperTypes="#//PrimitiveLiteralExp">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An integer literal, e.g. 42."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="integerSymbol" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RealLiteralExp" eSuperTypes="#//PrimitiveLiteralExp">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A real (floating-point) literal, e.g. 3.14."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="realSymbol" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnlimitedNaturalLiteralExp" eSuperTypes="#//PrimitiveLiteralExp">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An unlimited natural literal: a non-negative integer or the special value * (unlimited). The value -1 represents *."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unlimitedNaturalSymbol"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringLiteralExp" eSuperTypes="#//PrimitiveLiteralExp">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A string literal, e.g. 'hello'."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stringSymbol" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanLiteralExp" eSuperTypes="#//PrimitiveLiteralExp">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A boolean literal: true or false."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="booleanSymbol" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NullLiteralExp" eSuperTypes="#//PrimitiveLiteralExp">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The null literal, representing the single instance of OclVoid."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InvalidLiteralExp" eSuperTypes="#//LiteralExp">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The invalid literal, representing the single instance of OclInvalid. Signals an evaluation error."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumLiteralExp" eSuperTypes="#//LiteralExp">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A reference to an enumeration literal, e.g. Color::red (OCL v2.4 Section 8.3.10)."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referredLiteral" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EEnumLiteral">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The Ecore enumeration literal being referenced."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CollectionLiteralExp" eSuperTypes="#//LiteralExp">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A collection literal, e.g. Set{1, 2, 3} or Sequence{1..10} (OCL v2.4 Section 8.3.11)."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//CollectionKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedParts" upperBound="-1"
        eType="#//CollectionLiteralPart" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TupleLiteralExp" eSuperTypes="#//LiteralExp">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A tuple literal, e.g. Tuple{name = 'John', age = 30} (OCL v2.4 Section 8.3.12)."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedParts" upperBound="-1"
        eType="#//TupleLiteralPart" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MapLiteralExp" eSuperTypes="#//LiteralExp">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A map literal, e.g. Map{'a' = 1, 'b' = 2}. OCL v2.5 extension."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedParts" upperBound="-1"
        eType="#//MapLiteralPart" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IfExp" eSuperTypes="#//OclExpression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A conditional expression: if condition then thenExp else elseExp endif (OCL v2.4 Section 8.3.13)."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedCondition" eType="#//OclExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedThen" eType="#//OclExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedElse" eType="#//OclExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LetExp" eSuperTypes="#//OclExpression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A let expression that introduces a local variable: let x : T = initExp in bodyExp (OCL v2.4 Section 8.3.14)."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedVariable" eType="#//Variable"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The variable introduced by this let expression."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedIn" eType="#//OclExpression"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The body expression in which the variable is in scope."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariableExp" eSuperTypes="#//OclExpression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A reference to a previously declared variable (self, iterator, let, result, parameter) (OCL v2.4 Section 8.3.15)."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referredVariable" eType="#//Variable">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The variable declaration this expression refers to."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeExp" eSuperTypes="#//OclExpression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A type literal used in oclIsKindOf(), oclAsType(), etc. (OCL v2.4 Section 8.3.16)."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referredType" eType="#//OclType">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The OCL type this expression refers to."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MessageExp" eSuperTypes="#//OclExpression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An OclMessage expression representing an asynchronous operation call or signal send in a postcondition (OCL v2.4 Section 8.3.17)."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedTarget" eType="#//OclExpression"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The target object expression of the message send."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedArguments" upperBound="-1"
        eType="#//OclExpression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedCalledOperation" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EOperation">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The operation being called via message send, or null if this is a signal send."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedSentSignal" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClassifier">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The signal being sent, or null if this is an operation call. Typed as EClassifier since Ecore has no signal concept."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variable">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A variable declaration used as self, iterator variable, let variable, iterate accumulator, or operation parameter (OCL v2.4 Section 8.3)."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//OclType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedInit" eType="#//OclExpression"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Optional initialization expression. Required for let variables and iterate accumulators."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constraint">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A named OCL constraint (invariant, pre/postcondition, body, init, derive, or def) attached to a model element."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//ConstraintKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specification" eType="#//OclExpression"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The OCL expression that forms the body of this constraint."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contextClassifier" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClassifier">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The classifier context for inv and def constraints."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contextOperation" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EOperation">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The operation context for pre, post, and body constraints."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contextProperty" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStructuralFeature">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The property context for init and derive constraints."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isStatic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="True if declared with 'static' keyword (OCL v2.4 §12.12.6). Static defs are classifier-level rather than instance-level."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CollectionLiteralPart" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Abstract base for parts of a collection literal: either a single item or a range (OCL v2.4 Section 8.3.11)."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CollectionItem" eSuperTypes="#//CollectionLiteralPart">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A single element in a collection literal, e.g. the '1' in Set{1, 2}."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedItem" eType="#//OclExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CollectionRange" eSuperTypes="#//CollectionLiteralPart">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A range in a collection literal, e.g. the '1..10' in Sequence{1..10}."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedFirst" eType="#//OclExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedLast" eType="#//OclExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TupleLiteralPart">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A name-value pair in a tuple literal, e.g. 'name = 'John'' in Tuple{name = 'John', age = 30}."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//OclType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedInit" eType="#//OclExpression"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The value expression for this tuple part."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MapLiteralPart">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A key-value pair in a map literal. OCL v2.5 extension."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedKey" eType="#//OclExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedValue" eType="#//OclExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TuplePart">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A named, typed part in a TupleType definition. Defines the structure of a tuple type."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//OclType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StateExp" eSuperTypes="#//OclExpression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A reference to a UML State, used as argument to oclIsInState(). The referredState is typed generically as EObject to avoid a UML metamodel dependency (OCL v2.4 Section 7.5.10)."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referredState" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The UML State being referenced. Typed as EObject; the ocl.uml bundle casts to the concrete UML State type at runtime."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
